### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by 4dv0c47** [DehaiZhao/text_deskewing#1]
When I run `rotation_demo.py` I get the following error:

```
Traceback (most recent call last):
  File "rotation_demo.py", line 51, in <module>
    lines1 = lines[:,0,:]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by stijojoseph** [comment]
> When I run `rotation_demo.py` I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "rotation_demo.py", line 51, in <module>
>     lines1 = lines[:,0,:]
> TypeError: 'NoneType' object has no attribute '__getitem__'
> ```

**Comment by stijojoseph** [comment]
same error any body solved it?
